// Code generated by "stringer -tags universalrelv2 -type=DependencyType -output=dependencyType_universal_v2_string.go"; DO NOT EDIT.

package lingo

import "strconv"

const _DependencyType_name = "NoDepTypeAclAclRelclAdvClAdvModAModApposAuxAuxPassCaseCCCCPreconjCCompClfCompoundCompoundPrtConjCopCSubjCSubjPassDepDetDetPredetDiscourseDislocatedExplFixedFlatFlatForeignGoesWithIObjListMarkNModNModNPModNModPossNModTModNSubjNSubjPassNumModObjOblOblNPModOblTModOrphanParataxisPunctReparandumRootVocativeXCompMAXDEPTYPE"

var _DependencyType_index = [...]uint16{0, 9, 12, 20, 25, 31, 35, 40, 43, 50, 54, 56, 65, 70, 73, 81, 92, 96, 99, 104, 113, 116, 119, 128, 137, 147, 151, 156, 160, 171, 179, 183, 187, 191, 195, 204, 212, 220, 225, 234, 240, 243, 246, 254, 261, 267, 276, 281, 291, 295, 303, 308, 318}

func (i DependencyType) String() string {
	if i >= DependencyType(len(_DependencyType_index)-1) {
		return "DependencyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DependencyType_name[_DependencyType_index[i]:_DependencyType_index[i+1]]
}
